### ISSUE TITLE
esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7280

### ISSUE THREAD

**Issue by PhixedAP** [dahmadjid/Firebase-idf#2]
Hello,
first, thanks a lot for your library.
I was wondering if you now any solution for below issue which happens quiet frequently. Sometimes I am able to connect, but 4/5 times it does not work. This is the log I receive with mbedtls debug activated:

...

`I (120482) mbedtls: ssl_tls.c:2792 in_left: 0, nb_want: 5

I (120492) mbedtls: ssl_tls.c:2816 in_left: 0, nb_want: 5
I (120492) mbedtls: ssl_tls.c:2817 ssl->f_recv(_timeout)() returned 0 (-0x0000)
W (120502) mbedtls: ssl_tls.c:5084 mbedtls_ssl_fetch_input() returned -29312 (-0x7280)
W (120512) mbedtls: ssl_tls.c:4455 ssl_get_next_record() returned -29312 (-0x7280)
W (120512) mbedtls: ssl_cli.c:1691 mbedtls_ssl_read_record() returned -29312 (-0x7280)
I (120532) mbedtls: ssl_tls.c:8219 <= handshake
E (120532) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7280
I (120532) esp-tls-mbedtls: Certificate verified.
E (120542) esp-tls: Failed to open new connection
E (120552) TRANS_SSL: Failed to open a new connection
E (120592) HTTP_CLIENT: Connection failed, sock < 0
E (120592) HTTP_CLIENT: Error while performing request esp_err_t code=0x7002 | status_code=0
E (120592) HTTP_CLIENT: request: url=https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=(removed api key) 
method=1 
post_field={"email":"(removed email)", "password":"(removed password)", "returnSecureToken": true}
4��?4��?2) HTTP_CLIENT: response=
`

Calls to xPortGetFreeHeapSize() always returned values above 100.000

Thanks in advance for any help.

Cheers
Phil

**Comment by dahmadjid** [comment]
Hi, thank you for using my library and i am really grateful for the bug
report. i will make sure to look into it asap.
I will be really happy if you can give me a code snippet that caused this
bug so i can test it and make sure its working. in the meantime i will look
into it and get back to you as soon as i find anything. thank you!
Best regards,
Madjid

**Comment by PhixedAP** [comment]
Hey,
thanks for your reply.
I actually figured out the bug.
Issue is connected to mbed_tls library and an old esp-idf framework and/or old gcc version.
More information can be found here: https://github.com/espressif/esp-idf/issues/4127
I solved my problems by upgrading from esp-idf v4.0 to esp-idf v4.4.2. 
Now, so far, connecting to google cloud (refresh token, auth token, rtdb) works every time :) 
Cheers
Phil

**Comment by dahmadjid** [comment]
Great to hear that. Thanks for the contributing!

**Comment by ivancmz** [comment]
> mbed_tls library and an old esp-idf framework and/or old gcc version.
> More information can be found here: [espressif/esp-idf#4127](https://github.com/espressif/esp-idf/issues/4127)
> I solved my problems by upgrading from esp-idf v4.0 to esp-idf v4.4.

I'm having this exact same issue @80MHz on esp-idf v4.4.1 and v4.4.2, tried internal RAM and FreeRTOS on single core, but I still get the issue. With 160MHz clock the issue seems to go away or occur less... any ideas?

**Comment by MATTYGILO** [comment]
@ivancmz Did you fix the error?

**Comment by ivancmz** [comment]
> @ivancmz Did you fix the error?

Hi, not entirely, I'm convinced it has more to do with memory than speed, but like I said, changing to 160MHz made it work and I haven't done much in this project since, but I have to make some changes in the next few weeks and I will probably tackle this again... I'm now moving to IDF 4.4.5, and adding more functionality so... I'll let you know how it goes.
